<a href="https://colab.research.google.com/github/MuhammadSarimUmer/Python-Learning/blob/master/Day02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv('sales_data.csv',parse_dates=['date'],dtype={
    'returned':'category',
    'quantity':'category'
})

In [5]:
df.head(5)

,transaction_id,date,product_id,store_id,customer_id,quantity,discount,returned
0,T0000001,2023-08-02,P004681,S004,C010043,3,0.0,0
1,T0000002,2020-08-16,P006662,S003,C022472,1,0.0,0
2,T0000003,2020-02-21,P043402,S005,C016135,4,0.0,0
3,T0000004,2024-02-27,P029875,S003,C005605,3,NaN,1
4,T0000005,2021-07-17,P002476,S003,C005857,4,0.0,0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 8 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   transaction_id  50000 non-null  object
 1   date            50000 non-null  datetime64[ns]
 2   product_id      50000 non-null  object
 3   store_id        50000 non-null  object
 4   customer_id     48156 non-null  object
 5   quantity        50000 non-null  category
 6   discount        47417 non-null  float64
 7   returned        50000 non-null  category
dtypes: category(2), datetime64[ns](1), float64(1), object(4)
memory usage: 2.4+ MB

In [7]:
df = df.dropna(subset=['customer_id'])

In [8]:
df.isna().sum()

transaction_id       0
date                 0
product_id           0
store_id             0
customer_id          0
quantity             0
discount          2478
returned             0
dtype: int64

In [9]:
missig = df[df['discount'].isnull()]
df['discount'] = df['discount'].fillna(0)

In [10]:
df['customer_id']=df['customer_id'].str.strip().str.lower()

In [11]:
df = pd.read_csv('retail_sales_dataset.csv',parse_dates=['Date'])
df.head(10)

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
0,1,2023-11-24,CUST001,Male,34,Beauty,3,50,150
1,2,2023-02-27,CUST002,Female,26,Clothing,2,500,1000
2,3,2023-01-13,CUST003,Male,50,Electronics,1,30,30
3,4,2023-05-21,CUST004,Male,37,Clothing,1,500,500
4,5,2023-05-06,CUST005,Male,30,Beauty,2,50,100
5,6,2023-04-25,CUST006,Female,45,Beauty,1,30,30
6,7,2023-03-13,CUST007,Male,46,Clothing,2,25,50
7,8,2023-02-22,CUST008,Male,30,Electronics,4,25,100
8,9,2023-12-13,CUST009,Male,63,Electronics,2,300,600
9,10,2023-10-07,CUST010,Female,52,Clothing,4,50,200

In [12]:
df_sorted = df.sort_values(by = ['Total Amount','Price per Unit'], ascending=[True,True])
df_sorted.head(10)

,Transaction ID,Date,Customer ID,Gender,Age,Product Category,Quantity,Price per Unit,Total Amount
43,44,2023-02-19,CUST044,Female,22,Clothing,1,25,25
102,103,2023-01-17,CUST103,Female,59,Clothing,1,25,25
184,185,2023-02-27,CUST185,Male,24,Clothing,1,25,25
190,191,2023-10-18,CUST191,Male,64,Beauty,1,25,25
200,201,2023-10-09,CUST201,Male,56,Electronics,1,25,25
203,204,2023-09-28,CUST204,Male,39,Beauty,1,25,25
204,205,2023-11-07,CUST205,Female,43,Clothing,1,25,25
205,206,2023-08-05,CUST206,Male,61,Clothing,1,25,25
222,223,2023-02-02,CUST223,Female,64,Clothing,1,25,25
229,230,2023-04-23,CUST230,Male,54,Beauty,1,25,25

In [14]:
df.shape

(1000, 9)

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Transaction ID    1000 non-null   int64
 1   Date              1000 non-null   datetime64[ns]
 2   Customer ID       1000 non-null   object
 3   Gender            1000 non-null   object
 4   Age               1000 non-null   int64
 5   Product Category  1000 non-null   object
 6   Quantity          1000 non-null   int64
 7   Price per Unit    1000 non-null   int64
 8   Total Amount      1000 non-null   int64
dtypes: datetime64[ns](1), int64(5), object(3)
memory usage: 70.4+ KB

In [24]:
df[['Price per Unit','Total Amount']].describe()

       Price per Unit  Total Amount
count     1000.000000   1000.000000
mean       179.890000    456.000000
std        189.681356    559.997632
min         25.000000     25.000000
25%         30.000000     60.000000
50%         50.000000    135.000000
75%        300.000000    900.000000
max        500.000000   2000.000000

In [27]:
df['Total Amount'].mean()
df['Total Amount'].median()

135.0

In [28]:
df['Total Amount'].skew()

np.float64(1.3761282440171279)

In [29]:
df.groupby('Product Category')['Total Amount'].describe()

,count,mean,std,min,25%,50%,75%,max
Product Category,,,,,,,,
Beauty,307.0,467.475570,563.612788,25.0,75.0,120.0,900.0,2000.0
Clothing,351.0,443.247863,550.695917,25.0,60.0,120.0,600.0,2000.0
Electronics,342.0,458.786550,567.540150,25.0,60.0,150.0,900.0,2000.0

In [30]:
Q1 = df['Total Amount'].quantile(0.25)
Q3 = df['Total Amount'].quantile(0.75)
IQR = Q3 - Q1
Q1,Q3,IQR

(np.float64(60.0), np.float64(900.0), np.float64(840.0))