<a href="https://colab.research.google.com/github/MuhammadSarimUmer/Python-Learning/blob/master/Pandas2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [66]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2026.1)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [67]:
import pandas as pd

In [68]:
try:
  df = pd.read_csv('sample_data.csv',parse_dates=['order_date'],dtype={
      'payment_method': 'category'
  })
  print(df.info())
  print(df.describe())
except:
  print('Error reading file')

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 12 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          5000 non-null   int64
 1   order_date        5000 non-null   datetime64[ns]
 2   customer_id       5000 non-null   int64
 3   product_category  5000 non-null   object
 4   region            5000 non-null   object
 5   quantity          5000 non-null   int64
 6   unit_price        5000 non-null   float64
 7   discount          5000 non-null   float64
 8   payment_method    5000 non-null   category
 9   delivery_days     5000 non-null   int64
 10  customer_rating   5000 non-null   float64
 11  revenue           5000 non-null   float64
dtypes: category(1), datetime64[ns](1), float64(4), int64(4), object(2)
memory usage: 434.8+ KB
None
           order_id           order_date  customer_id     quantity  \
count   5000.000000                 5000  5000.000000  5000.000000
mean   12500.500000  2028-11-04 12:00:00  1505.701200     4.044800
min    10001.000000  2022-01-01 00:00:00  1000.000000     1.000000
25%    11250.750000  2025-06-03 18:00:00  1253.000000     2.000000
50%    12500.500000  2028-11-04 12:00:00  1510.000000     4.000000
75%    13750.250000  2032-04-07 06:00:00  1761.000000     6.000000
max    15000.000000  2035-09-09 00:00:00  1999.000000     7.000000
std     1443.520003                  NaN   290.836902     2.020398

        unit_price     discount  delivery_days  customer_rating      revenue
count  5000.000000  5000.000000    5000.000000      5000.000000  5000.000000
mean    308.418774     0.179984       6.118800         2.973980  1021.955148
min      15.150000     0.000000       1.000000         1.000000    11.210000
25%     161.895000     0.090000       3.000000         2.000000   354.527500
50%     309.890000     0.180000       6.000000         3.000000   796.650000
75%     455.557500     0.270000       9.000000         4.000000  1515.690000
max     599.960000     0.350000      11.000000         5.000000  4119.330000
std     169.259369     0.101404       3.153264         1.157722   825.584219

In [69]:
print(df['revenue'].quantile([0.25,0.5,0.75]))

0.25     354.5275
0.50     796.6500
0.75    1515.6900
Name: revenue, dtype: float64

In [70]:
print(df['revenue'].mean())
print(df['revenue'].median())

1021.955148
796.65

In [71]:
print(df['revenue'].skew())

1.0017064603000962

In [72]:
desc = df.groupby('product_category')['revenue'].describe()

In [73]:
total_sum = df.groupby('product_category')['revenue'].sum()
desc.insert(1,'sum',total_sum)

desc

,count,sum,mean,std,min,25%,50%,75%,max
product_category,,,,,,,,,
Beauty,723.0,765860.88,1059.281992,867.590231,20.94,331.585,821.64,1662.825,4005.93
Clothing,1531.0,1531931.72,1000.608570,806.210745,11.21,349.940,785.22,1477.230,3928.63
Electronics,1777.0,1829899.22,1029.768835,831.796825,13.26,365.670,796.49,1499.280,4119.33
Home,969.0,982083.92,1013.502497,812.271060,13.01,348.350,802.83,1488.750,3640.56

In [74]:
df.groupby('product_category')['revenue'].mean()

product_category
Beauty         1059.281992
Clothing       1000.608570
Electronics    1029.768835
Home           1013.502497
Name: revenue, dtype: float64

In [75]:
Q1 = df['revenue'].quantile(0.25)
Q3 = df['revenue'].quantile(0.75)

IQR = Q3 - Q1
print(IQR, Q1,Q3)

df = df.set_index('order_date')

1161.1625000000001 354.5275 1515.69

In [76]:

monthly_revenue = df['revenue'].resample('YE').sum()
monthly_revenue.pct_change() * 100

order_date
2022-12-31          NaN
2023-12-31    -1.589060
2024-12-31    -0.739695
2025-12-31    -3.691207
2026-12-31    10.453721
2027-12-31    -0.056366
2028-12-31    -2.410220
2029-12-31    -4.671833
2030-12-31     7.973856
2031-12-31    -5.835147
2032-12-31     5.840863
2033-12-31     5.727359
2034-12-31   -11.128776
2035-12-31   -34.276606
Freq: YE-DEC, Name: revenue, dtype: float64

In [77]:
Q1 = df['revenue'].quantile(0.25)
Q3 = df['revenue'].quantile(0.75)
IQR = Q3 - Q1
print(IQR,Q3,Q1)
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR
print(lower,upper)
# outliers_iqr = df[(df['revenue'] < lower) | (df['revenue'] > upper)]
# outliers_iqr.shape

df = df[(df['revenue'] > lower) & (df['revenue'] < upper)]
df.shape

1161.1625000000001 1515.69 354.5275
-1387.2162500000002 3257.43375

(4933, 11)

In [78]:
df.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 4933 entries, 2022-01-01 to 2035-09-09
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          4933 non-null   int64
 1   customer_id       4933 non-null   int64
 2   product_category  4933 non-null   object
 3   region            4933 non-null   object
 4   quantity          4933 non-null   int64
 5   unit_price        4933 non-null   float64
 6   discount          4933 non-null   float64
 7   payment_method    4933 non-null   category
 8   delivery_days     4933 non-null   int64
 9   customer_rating   4933 non-null   float64
 10  revenue           4933 non-null   float64
dtypes: category(1), float64(4), int64(4), object(2)
memory usage: 428.9+ KB

In [88]:
numerical_df = df[['quantity','unit_price','discount','delivery_days','customer_rating','revenue']]
print(numerical_df.corr())

                 quantity  unit_price  discount  delivery_days  \
quantity         1.000000   -0.027078  0.015180      -0.010346
unit_price      -0.027078    1.000000  0.034342       0.014348
discount         0.015180    0.034342  1.000000      -0.000289
delivery_days   -0.010346    0.014348 -0.000289       1.000000
customer_rating  0.017103    0.002773  0.016647      -0.015912
revenue          0.613846    0.670034 -0.103357       0.002870

                 customer_rating   revenue
quantity                0.017103  0.613846
unit_price              0.002773  0.670034
discount                0.016647 -0.103357
delivery_days          -0.015912  0.002870
customer_rating         1.000000  0.007296
revenue                 0.007296  1.000000